[package]
name = "protos"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.1.0"
prost = "0.12"
prost-types = "0.12"
pbjson = "0.6"
pbjson-types = "0.6"
serde = "1.0"
chrono = { version = "0.4.31", features = ["serde", "rustc-serialize"] }
